---
- name: Check if we are in a chroot
  shell: 'if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then echo True; else echo False; fi'
  failed_when: False
  changed_when: False
  register: chroot

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: vars

- include: el7/main.yml
  when: ansible_os_family == "RedHat"
        and ansible_distribution_major_version|int == 7

- include: el6/main.yml
  when: ansible_os_family == "RedHat"
        and ansible_distribution_major_version|int == 6
