---
- name: Ensure SSHD is installed
  package:
    name: openssh-server
    state: installed

- name: Configure sshd
  template:
    dest: /etc/ssh/sshd_config
    src: templates/common/sshd_config.j2
  notify: restart sshd

- name: Gather SSH host keys
  shell: find /etc/ssh/ -name "ssh_host*" ! -name "*.pub"
  register: ssh_host_keys
  changed_when: False
  failed_when: False
  tags:
    - skip_ansible_lint

- name: Fix SSH host key permissions
  file:
    path: "{{ item }}"
    mode: 0600
  with_items: "{{ ssh_host_keys.stdout_lines }}"

- name: Ensure firewall port is opened
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  when: ansible_distribution_major_version == '7'

- name: Ensure firewall port is opened
  iptables:
    chain: "INPUT"
    jump: "ACCEPT"
    protocol: tcp
    destination_port: 22
  when: ansible_distribution_major_version == '6'
  notify: save iptables

- name: Enable sshd service
  service:
    name: sshd
    enabled: True
